apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: docker-poc
  name: docker-poc-ingress
  annotations:
    # Fix 502 on redirect from Azure AD login
    # See: https://andrewlock.net/fixing-nginx-upstream-sent-too-big-header-error-when-running-an-ingress-controller-in-kubernetes/
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  tls:
  - hosts:
    - www.docker-poc.local
    - rabbitmq.docker-poc.local
    secretName: docker-poc-tls
  rules:
  - host: www.docker-poc.local
    http:
      paths:
      - backend:
          serviceName: docker-poc-web
          servicePort: 80
  - host: rabbitmq.docker-poc.local
    http:
      paths:
      - backend:
          serviceName: docker-poc-rabbitmq
          servicePort: 80